/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */
import type {
  ErrorResponse,
  GetVoteParams,
  GetVoteResponse,
  VoteMovieParams,
  VoteMovieResponse
} from '../../model';

import { customInstance } from '../../lib/orval-client';

export type getVoteResponse200 = {
  data: GetVoteResponse
  status: 200
}

export type getVoteResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getVoteResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getVoteResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getVoteResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getVoteResponseSuccess = (getVoteResponse200) & {
  headers: Headers;
};
export type getVoteResponseError = (getVoteResponse401 | getVoteResponse403 | getVoteResponse404 | getVoteResponse500) & {
  headers: Headers;
};

export type getVoteResponse = (getVoteResponseSuccess | getVoteResponseError)

export const getGetVoteUrl = (params?: GetVoteParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/party/vote?${stringifiedParams}` : `/api/party/vote`
}

export const getVote = async (params?: GetVoteParams, options?: RequestInit): Promise<getVoteResponse> => {
  
  return customInstance<getVoteResponse>(getGetVoteUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type voteMovieResponse200 = {
  data: VoteMovieResponse
  status: 200
}

export type voteMovieResponse401 = {
  data: ErrorResponse
  status: 401
}

export type voteMovieResponse403 = {
  data: ErrorResponse
  status: 403
}

export type voteMovieResponse404 = {
  data: ErrorResponse
  status: 404
}

export type voteMovieResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type voteMovieResponseSuccess = (voteMovieResponse200) & {
  headers: Headers;
};
export type voteMovieResponseError = (voteMovieResponse401 | voteMovieResponse403 | voteMovieResponse404 | voteMovieResponse500) & {
  headers: Headers;
};

export type voteMovieResponse = (voteMovieResponseSuccess | voteMovieResponseError)

export const getVoteMovieUrl = (params: VoteMovieParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/party/vote?${stringifiedParams}` : `/api/party/vote`
}

export const voteMovie = async (params: VoteMovieParams, options?: RequestInit): Promise<voteMovieResponse> => {
  
  return customInstance<voteMovieResponse>(getVoteMovieUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


