/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */
import type {
  VersionInfo
} from '../../model';

import { customInstance } from '../../lib/orval-client';

/**
 * @summary Get application version and git commit hash.
 */
export type getVersionResponse200 = {
  data: VersionInfo
  status: 200
}
    
export type getVersionResponseSuccess = (getVersionResponse200) & {
  headers: Headers;
};
;

export type getVersionResponse = (getVersionResponseSuccess)

export const getGetVersionUrl = () => {


  

  return `/api/system/version`
}

export const getVersion = async ( options?: RequestInit): Promise<getVersionResponse> => {
  
  return customInstance<getVersionResponse>(getGetVersionUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


