/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */
import type {
  ErrorResponse,
  GetRecommendationsParams,
  RecommendedMoviesResponse
} from '../../model';

import { customInstance } from '../../lib/orval-client';

/**
 * Returns a list of recommended movies based on user preferences or party context.
 * @summary Get movie recommendations
 */
export type getRecommendationsResponse200 = {
  data: RecommendedMoviesResponse
  status: 200
}

export type getRecommendationsResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getRecommendationsResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getRecommendationsResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getRecommendationsResponseSuccess = (getRecommendationsResponse200) & {
  headers: Headers;
};
export type getRecommendationsResponseError = (getRecommendationsResponse401 | getRecommendationsResponse404 | getRecommendationsResponse500) & {
  headers: Headers;
};

export type getRecommendationsResponse = (getRecommendationsResponseSuccess | getRecommendationsResponseError)

export const getGetRecommendationsUrl = (params?: GetRecommendationsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/recommend?${stringifiedParams}` : `/api/recommend`
}

export const getRecommendations = async (params?: GetRecommendationsParams, options?: RequestInit): Promise<getRecommendationsResponse> => {
  
  return customInstance<getRecommendationsResponse>(getGetRecommendationsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


