/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */

export type ApiError = {
  BadRequest: string;
} | {
  Unauthorized: string;
} | {
  Forbidden: string;
} | {
  NotFound: string;
} | {
  InternalServerError: string;
} | {
  Conflict: string;
};
