/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */

export interface CastMemberResponse {
  name: string;
  /** @nullable */
  profile_url?: string | null;
}
