/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response when creating a new party
 */
export interface CreatePartyResponse {
  /** The 4-character join code (e.g., "A1B2") */
  code: string;
  /** When the party was created */
  created_at: string;
  /** The unique party ID */
  party_id: string;
}
