/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response with current user info and token details
 */
export interface CurrentUserResponse {
  /** When the user was created */
  created_at: string;
  /** Whether this is a guest/oneshot user */
  is_guest: boolean;
  /** Token expiry timestamp (Unix seconds) */
  token_expires_at: number;
  /** Seconds until token expiry */
  token_expires_in: number;
  /** When the user was last updated */
  updated_at: string;
  /** The user's unique ID */
  user_id: string;
  /** The user's display name */
  username: string;
}
