/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response with current user info and token details
 */
export interface CurrentUserResponse {
  /** When the user was created */
  created_at: string;
  /** Whether this is a guest/oneshot user */
  is_guest: boolean;
  /**
   * Token expiry timestamp (Unix seconds)
This is optional because we can only get if user logged in via JWT; cookie-authenticated users won't have this field.
   * @nullable
   */
  token_expires_at?: number | null;
  /**
   * Seconds until token expiry
This is optional because we can only get if user logged in via JWT; cookie-authenticated users won't have this field.
   * @nullable
   */
  token_expires_in?: number | null;
  /** When the user was last updated */
  updated_at: string;
  /** The user's unique ID */
  user_id: string;
  /** The user's display name */
  username: string;
}
