/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Standard error response
 */
export interface ErrorResponse {
  /** Human-readable error message */
  error: string;
}
