/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response for GET /api/party/{party_id}/picks: your picks (movie IDs) for this party.
 */
export interface GetPicksResponse {
  /** TMDB movie IDs you have picked. Empty when not in Created/Picking. */
  movie_ids: number[];
}
