/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */
import type { RecommendationMethod } from './recommendationMethod';
import type { VectorType } from './vectorType';

export type GetRecommendationsParams = {
/**
 * (Optional) Party ID to get recommendations for a group.
 * @nullable
 */
party_id?: string | null;
/**
 * (Optional) Recommendation method to use.
- `reviews`: Based on user reviews.
- `semantic`: based on plot/meta similarity.
- `default`: Hybrid mix.
 */
method?: null | RecommendationMethod;
/**
 * (Optional) Vector type for semantic search.
- `plot`: Movie plots.
- `cast_crew`: Actors/Directors.
- `reviews`: User reviews.
- `combined`: All metrics.
 */
vector?: null | VectorType;
/**
 * (Optional) Number of movies to return (default: 3).
 * @minimum 0
 * @nullable
 */
limit?: number | null;
};
