/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */
import type { GetVoteResponseVoteTotals } from './getVoteResponseVoteTotals';

/**
 * Response for GET /api/party/{party_id}/vote: ballot and vote info for the current user.
 */
export interface GetVoteResponse {
  can_vote: boolean;
  /** Movie IDs the user can vote on (their ballot). Use on refresh / poll. */
  movie_ids: number[];
  /** Totals per movie (keys = movie_ids). Omitted when empty. */
  vote_totals: GetVoteResponseVoteTotals;
  /**
   * 1 = first round, 2 = top-3 round. None when not in Voting.
   * @nullable
   */
  voting_round?: number | null;
}
