/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */
import type { VoteTotals } from './voteTotals';

/**
 * Totals per movie (keys = movie_ids). Omitted when empty.
 */
export type GetVoteResponseVoteTotals = {[key: string]: VoteTotals};
