/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response when creating a guest user
 */
export interface GuestLoginResponse {
  /** The newly created user ID */
  user_id: string;
  /** The username */
  username: string;
}
