/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request to kick a member (leader only)
 */
export interface KickMemberRequest {
  /** The user ID of the member to kick */
  target_user_id: string;
}
