/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Information about a party member
 */
export interface MemberInfo {
  /** Whether this member is the party leader */
  is_leader: boolean;
  /** Whether this member has marked themselves as ready */
  is_ready: boolean;
  /** When the member joined the party */
  joined_at: string;
  /** The user's unique ID */
  user_id: string;
  /** The user's display name */
  username: string;
}
