/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response after starting a new round
 */
export interface NewRoundResponse {
  /** New join code for the round */
  code: string;
}
