/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */

export interface OAuthCallbackResponse {
  /** Unix timestamp when the token expires */
  expires_at: number;
  /** Seconds until expiration */
  expires_in: number;
  /** short-lived JWT for API calls */
  jwt: string;
  /** logged-in user ID */
  user_id: string;
  /**
   * user display name (if available)
   * @nullable
   */
  username?: string | null;
}
