/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */

/**
 * Vote totals per movie (only in Voting): movie_id → (likes, dislikes)
 * @nullable
 */
export type PartyResponseVoteStatus = {[key: string]: [number, number]} | null | null;
