/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */

/**
 * Party state for API responses
 */
export type PartyStateDto = typeof PartyStateDto[keyof typeof PartyStateDto];


export const PartyStateDto = {
  created: 'created',
  picking: 'picking',
  voting: 'voting',
  watching: 'watching',
  review: 'review',
  disbanded: 'disbanded',
} as const;
