/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */
import type { MemberInfo } from './memberInfo';

/**
 * Response with list of party members
 */
export interface PartyMembersResponse {
  /** Whether all members are ready */
  all_ready: boolean;
  /**
   * Total count of members
   * @minimum 0
   */
  count: number;
  /** List of all members in the party */
  members: MemberInfo[];
  /**
   * Number of members who are ready
   * @minimum 0
   */
  ready_count: number;
}
