/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */
import type { PartyStateDto } from './partyStateDto';

/**
 * Response with party details
 */
export interface PartyResponse {
  /**
   * The join code (only present in Created state)
   * @nullable
   */
  code?: string | null;
  /** When the party was created */
  created_at: string;
  /** The unique party ID */
  id: string;
  /** The party leader's user ID */
  leader_id: string;
  /** Current state of the party */
  state: PartyStateDto;
}
