/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */

/**
 * Ratings for the selected movie in the Review phase: user_id → rating
 * @nullable
 */
export type PartyResponseReviewRatings = {[key: string]: number} | null | null;
