/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */
import type { PartyStateDto } from './partyStateDto';

/**
 * Response after advancing to next phase
 */
export interface PhaseAdvanceResponse {
  /** New party state after advancing */
  new_state: PartyStateDto;
}
