/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */

export type PickMovieParams = {
/**
 * Movie ID to update taste for.
 */
movie_id: number;
/**
 * (Optional) Liked status. Defaults to true.
 */
liked?: boolean;
/**
 * (Optional) Numeric rating for the movie.
 */
rating?: number;
/**
 * Optional party ID (UUID). If omitted, the system auto-selects from session.
 */
party_id?: string;
};
