/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response after toggling ready state
 */
export interface ReadyStateResponse {
  /** Whether all members are now ready */
  all_ready: boolean;
}
