/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */
import type { MovieResponse } from './movieResponse';

export interface RecommendedMoviesResponse {
  recommended_movies: MovieResponse[];
}
