/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */
import type { RecommendationMethod } from './recommendationMethod';
import type { VectorType } from './vectorType';

export interface RecommendationQuery {
  /**
   * (Optional) Number of movies to return (default: 3).
   * @minimum 0
   * @nullable
   */
  limit?: number | null;
  method?: null | RecommendationMethod;
  /**
   * (Optional) Party ID to get recommendations for a group.
   * @nullable
   */
  party_id?: string | null;
  vector?: null | VectorType;
}
