/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */

export type RecommendationMethod = typeof RecommendationMethod[keyof typeof RecommendationMethod];


export const RecommendationMethod = {
  reviews: 'reviews',
  semantic: 'semantic',
  default: 'default',
} as const;
