/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request to rename a user
 */
export interface RenameUserRequest {
  /** The new username (max 32 characters) */
  new_username: string;
}
