/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */

export type RenameUserParams = {
/**
 * New username (3–32 characters).
 */
name: string;
};
