/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response for renewing a JWT token
 */
export interface RenewJwtResponse {
  /** Newly issued JWT string */
  jwt: string;
  /** Unix timestamp when the token expires */
  token_expires_at: number;
  /** Seconds until expiration */
  token_expires_in: number;
}
