/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */

export type SearchMoviesParams = {
/**
 * Search string
 */
query: string;
/**
 * Page number (1-based)
 */
page?: number;
};
