/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */

export type SearchMoviesParams = {
/**
 * Movie title to search for.
 */
title: string;
/**
 * (Optional) Page number for search results. Defaults to 1.
 */
page?: number;
};
