/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */

export interface SearchFilter {
  exclude_genres: string[];
  include_genres: string[];
  /** @nullable */
  max_runtime?: number | null;
  /** @nullable */
  max_year?: number | null;
  /** @nullable */
  min_runtime?: number | null;
  /** @nullable */
  min_year?: number | null;
}
