/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */
import type { MovieResponse } from './movieResponse';

export interface SearchResponse {
  movies: MovieResponse[];
}
