/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request to set ready state
 */
export interface SetReadyRequest {
  is_ready: boolean;
}
