/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */

export type TransferLeadershipParams = {
/**
 * User ID of the new party leader.
 */
new_leader_id: string;
/**
 * Optional party ID (UUID). If omitted, the system auto-selects from session.
 */
party_id?: string;
};
