/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request to transfer leadership
 */
export interface TransferLeadershipRequest {
  /** The user ID of the new leader */
  new_leader_id: string;
}
