/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request to update user taste for a movie
 */
export interface UpdateTasteRequest {
  /** Whether the user liked the movie (true = like, false = dislike) */
  liked: boolean;
}
