/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * API-facing user preferences response (genre names, not IDs)
 */
export interface UserPreferencesResponse {
  created_at: string;
  exclude_genres: string[];
  include_genres: string[];
  release_year_flex: number;
  /** @nullable */
  target_release_year?: number | null;
  updated_at: string;
}
