/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */

export type VectorType = typeof VectorType[keyof typeof VectorType];


export const VectorType = {
  plot: 'plot',
  cast_crew: 'cast_crew',
  reviews: 'reviews',
  combined: 'combined',
} as const;
