/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Per-movie vote totals (for GET /vote)
 */
export interface VoteTotals {
  /** @minimum 0 */
  dislikes: number;
  /** @minimum 0 */
  likes: number;
}
