/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */

export type VoteMovieParams = {
/**
 * Movie ID being voted on.
 */
movie_id: number;
/**
 * Whether the vote is a like (true) or dislike (false).
 */
like: boolean;
/**
 * Optional party ID (UUID). If omitted, the system auto-selects from session.
 */
party_id?: string;
};
