/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */

export interface VoteMovieResponse {
  /** @minimum 0 */
  dislikes: number;
  /**
   * Current vote totals for the movie
   * @minimum 0
   */
  likes: number;
}
