/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */
import { customInstance } from '../../lib/orval-client';

/**
 * @summary WebSocket upgrade endpoint. Requires authentication via cookie.
 */
export type websocketResponse101 = {
  data: void
  status: 101
}

export type websocketResponse401 = {
  data: void
  status: 401
}
    
;
export type websocketResponseError = (websocketResponse101 | websocketResponse401) & {
  headers: Headers;
};

export type websocketResponse = (websocketResponseError)

export const getWebsocketUrl = () => {


  

  return `/api/ws`
}

export const websocket = async ( options?: RequestInit): Promise<websocketResponse> => {
  
  return customInstance<websocketResponse>(getWebsocketUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


