/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */
import type {
  ErrorResponse
} from '../../model';


export type websocketControllerResponse200 = {
  data: void
  status: 200
}

export type websocketControllerResponse400 = {
  data: void
  status: 400
}

export type websocketControllerResponse401 = {
  data: void
  status: 401
}

export type websocketControllerResponse406 = {
  data: void
  status: 406
}

export type websocketControllerResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type websocketControllerResponseSuccess = (websocketControllerResponse200) & {
  headers: Headers;
};
export type websocketControllerResponseError = (websocketControllerResponse400 | websocketControllerResponse401 | websocketControllerResponse406 | websocketControllerResponse500) & {
  headers: Headers;
};

export type websocketControllerResponse = (websocketControllerResponseSuccess | websocketControllerResponseError)

export const getWebsocketControllerUrl = () => {


  

  return `/api/ws`
}

export const websocketController = async ( options?: RequestInit): Promise<websocketControllerResponse> => {
  
  const res = await fetch(getWebsocketControllerUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: websocketControllerResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as websocketControllerResponse
}


