/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */
import type {
  ErrorResponse
} from '../../model';

import customInstance from '../../lib/orval-client';

export type websocketControllerResponse200 = {
  data: void
  status: 200
}

export type websocketControllerResponse400 = {
  data: void
  status: 400
}

export type websocketControllerResponse401 = {
  data: ErrorResponse
  status: 401
}

export type websocketControllerResponse406 = {
  data: void
  status: 406
}
    
export type websocketControllerResponseSuccess = (websocketControllerResponse200) & {
  headers: Headers;
};
export type websocketControllerResponseError = (websocketControllerResponse400 | websocketControllerResponse401 | websocketControllerResponse406) & {
  headers: Headers;
};

export type websocketControllerResponse = (websocketControllerResponseSuccess | websocketControllerResponseError)

export const getWebsocketControllerUrl = () => {


  

  return `/api/ws`
}

export const websocketController = async ( options?: RequestInit): Promise<websocketControllerResponse> => {
  
  return customInstance<websocketControllerResponse>(getWebsocketControllerUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


