/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */
import type {
  AdvancePhaseParams,
  DisbandPartyParams,
  ErrorResponse,
  KickMemberParams,
  TransferLeadershipParams
} from '../../model';

import { customInstance } from '../../lib/orval-client';

export type advancePhaseResponse200 = {
  data: void
  status: 200
}

export type advancePhaseResponse400 = {
  data: ErrorResponse
  status: 400
}

export type advancePhaseResponse403 = {
  data: ErrorResponse
  status: 403
}

export type advancePhaseResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type advancePhaseResponseSuccess = (advancePhaseResponse200) & {
  headers: Headers;
};
export type advancePhaseResponseError = (advancePhaseResponse400 | advancePhaseResponse403 | advancePhaseResponse404) & {
  headers: Headers;
};

export type advancePhaseResponse = (advancePhaseResponseSuccess | advancePhaseResponseError)

export const getAdvancePhaseUrl = (params?: AdvancePhaseParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/party/advance?${stringifiedParams}` : `/api/party/advance`
}

export const advancePhase = async (params?: AdvancePhaseParams, options?: RequestInit): Promise<advancePhaseResponse> => {
  
  return customInstance<advancePhaseResponse>(getAdvancePhaseUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


export type disbandPartyResponse200 = {
  data: void
  status: 200
}

export type disbandPartyResponse403 = {
  data: ErrorResponse
  status: 403
}

export type disbandPartyResponse404 = {
  data: void
  status: 404
}
    
export type disbandPartyResponseSuccess = (disbandPartyResponse200) & {
  headers: Headers;
};
export type disbandPartyResponseError = (disbandPartyResponse403 | disbandPartyResponse404) & {
  headers: Headers;
};

export type disbandPartyResponse = (disbandPartyResponseSuccess | disbandPartyResponseError)

export const getDisbandPartyUrl = (params?: DisbandPartyParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/party/disband?${stringifiedParams}` : `/api/party/disband`
}

export const disbandParty = async (params?: DisbandPartyParams, options?: RequestInit): Promise<disbandPartyResponse> => {
  
  return customInstance<disbandPartyResponse>(getDisbandPartyUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


export type kickMemberResponse200 = {
  data: void
  status: 200
}

export type kickMemberResponse403 = {
  data: ErrorResponse
  status: 403
}

export type kickMemberResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type kickMemberResponseSuccess = (kickMemberResponse200) & {
  headers: Headers;
};
export type kickMemberResponseError = (kickMemberResponse403 | kickMemberResponse404) & {
  headers: Headers;
};

export type kickMemberResponse = (kickMemberResponseSuccess | kickMemberResponseError)

export const getKickMemberUrl = (params: KickMemberParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/party/kick?${stringifiedParams}` : `/api/party/kick`
}

export const kickMember = async (params: KickMemberParams, options?: RequestInit): Promise<kickMemberResponse> => {
  
  return customInstance<kickMemberResponse>(getKickMemberUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


export type transferLeadershipResponse200 = {
  data: void
  status: 200
}

export type transferLeadershipResponse400 = {
  data: ErrorResponse
  status: 400
}

export type transferLeadershipResponse403 = {
  data: ErrorResponse
  status: 403
}

export type transferLeadershipResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type transferLeadershipResponseSuccess = (transferLeadershipResponse200) & {
  headers: Headers;
};
export type transferLeadershipResponseError = (transferLeadershipResponse400 | transferLeadershipResponse403 | transferLeadershipResponse404) & {
  headers: Headers;
};

export type transferLeadershipResponse = (transferLeadershipResponseSuccess | transferLeadershipResponseError)

export const getTransferLeadershipUrl = (params: TransferLeadershipParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/party/transfer-leadership?${stringifiedParams}` : `/api/party/transfer-leadership`
}

export const transferLeadership = async (params: TransferLeadershipParams, options?: RequestInit): Promise<transferLeadershipResponse> => {
  
  return customInstance<transferLeadershipResponse>(getTransferLeadershipUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


