/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import {
  PartyStateDto
} from '.././model';
import type {
  CreatePartyResponse,
  NewRoundResponse,
  PartyMembersResponse,
  PartyResponse,
  PhaseAdvanceResponse
} from '.././model';


export const getCreatePartyResponseMock = (overrideResponse: Partial< CreatePartyResponse > = {}): CreatePartyResponse => ({code: faker.string.alpha({length: {min: 10, max: 20}}), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', party_id: faker.string.uuid(), ...overrideResponse})

export const getJoinPartyResponseMock = (overrideResponse: Partial< CreatePartyResponse > = {}): CreatePartyResponse => ({code: faker.string.alpha({length: {min: 10, max: 20}}), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', party_id: faker.string.uuid(), ...overrideResponse})

export const getGetPartyResponseMock = (overrideResponse: Partial< PartyResponse > = {}): PartyResponse => ({code: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', id: faker.string.uuid(), leader_id: faker.string.uuid(), state: faker.helpers.arrayElement(Object.values(PartyStateDto)), ...overrideResponse})

export const getAdvancePhaseResponseMock = (overrideResponse: Partial< PhaseAdvanceResponse > = {}): PhaseAdvanceResponse => ({new_state: faker.helpers.arrayElement(Object.values(PartyStateDto)), ...overrideResponse})

export const getGetPartyMembersResponseMock = (overrideResponse: Partial< PartyMembersResponse > = {}): PartyMembersResponse => ({all_ready: faker.datatype.boolean(), count: faker.number.int({min: 0, max: undefined}), members: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({is_leader: faker.datatype.boolean(), is_ready: faker.datatype.boolean(), joined_at: faker.date.past().toISOString().slice(0, 19) + 'Z', user_id: faker.string.uuid(), username: faker.string.alpha({length: {min: 10, max: 20}})})), ready_count: faker.number.int({min: 0, max: undefined}), ...overrideResponse})

export const getStartNewRoundResponseMock = (overrideResponse: Partial< NewRoundResponse > = {}): NewRoundResponse => ({code: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})


export const getCreatePartyMockHandler = (overrideResponse?: CreatePartyResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CreatePartyResponse> | CreatePartyResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/party', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreatePartyResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getJoinPartyMockHandler = (overrideResponse?: CreatePartyResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CreatePartyResponse> | CreatePartyResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/party/join/:code', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getJoinPartyResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetPartyMockHandler = (overrideResponse?: PartyResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PartyResponse> | PartyResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/party/:partyId', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetPartyResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getAdvancePhaseMockHandler = (overrideResponse?: PhaseAdvanceResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PhaseAdvanceResponse> | PhaseAdvanceResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/party/:partyId/advance', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAdvancePhaseResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDisbandPartyMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/party/:partyId/disband', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getKickMemberMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/party/:partyId/kick', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getLeavePartyMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/party/:partyId/leave', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getGetPartyMembersMockHandler = (overrideResponse?: PartyMembersResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PartyMembersResponse> | PartyMembersResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/party/:partyId/members', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetPartyMembersResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getStartNewRoundMockHandler = (overrideResponse?: NewRoundResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<NewRoundResponse> | NewRoundResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/party/:partyId/new-round', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getStartNewRoundResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getToggleReadyMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/party/:partyId/ready', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getTransferLeadershipMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/party/:partyId/transfer-leadership', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}
export const getPartyMock = () => [
  getCreatePartyMockHandler(),
  getJoinPartyMockHandler(),
  getGetPartyMockHandler(),
  getAdvancePhaseMockHandler(),
  getDisbandPartyMockHandler(),
  getKickMemberMockHandler(),
  getLeavePartyMockHandler(),
  getGetPartyMembersMockHandler(),
  getStartNewRoundMockHandler(),
  getToggleReadyMockHandler(),
  getTransferLeadershipMockHandler()
]
