/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */
import type {
  CreatePartyResponse,
  ErrorResponse,
  GetPartyMembersParams,
  JoinPartyParams,
  LeavePartyParams,
  PartyMembersResponse,
  ReadyStateResponse,
  SetReadyParams
} from '../../model';

import { customInstance } from '../../lib/orval-client';

export type joinPartyResponse200 = {
  data: CreatePartyResponse
  status: 200
}

export type joinPartyResponse400 = {
  data: ErrorResponse
  status: 400
}

export type joinPartyResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type joinPartyResponseSuccess = (joinPartyResponse200) & {
  headers: Headers;
};
export type joinPartyResponseError = (joinPartyResponse400 | joinPartyResponse404) & {
  headers: Headers;
};

export type joinPartyResponse = (joinPartyResponseSuccess | joinPartyResponseError)

export const getJoinPartyUrl = (params: JoinPartyParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/party/join?${stringifiedParams}` : `/api/party/join`
}

export const joinParty = async (params: JoinPartyParams, options?: RequestInit): Promise<joinPartyResponse> => {
  
  return customInstance<joinPartyResponse>(getJoinPartyUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


export type leavePartyResponse200 = {
  data: void
  status: 200
}

export type leavePartyResponse400 = {
  data: ErrorResponse
  status: 400
}

export type leavePartyResponse404 = {
  data: void
  status: 404
}
    
export type leavePartyResponseSuccess = (leavePartyResponse200) & {
  headers: Headers;
};
export type leavePartyResponseError = (leavePartyResponse400 | leavePartyResponse404) & {
  headers: Headers;
};

export type leavePartyResponse = (leavePartyResponseSuccess | leavePartyResponseError)

export const getLeavePartyUrl = (params?: LeavePartyParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/party/leave?${stringifiedParams}` : `/api/party/leave`
}

export const leaveParty = async (params?: LeavePartyParams, options?: RequestInit): Promise<leavePartyResponse> => {
  
  return customInstance<leavePartyResponse>(getLeavePartyUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


export type getPartyMembersResponse200 = {
  data: PartyMembersResponse
  status: 200
}

export type getPartyMembersResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getPartyMembersResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type getPartyMembersResponseSuccess = (getPartyMembersResponse200) & {
  headers: Headers;
};
export type getPartyMembersResponseError = (getPartyMembersResponse403 | getPartyMembersResponse404) & {
  headers: Headers;
};

export type getPartyMembersResponse = (getPartyMembersResponseSuccess | getPartyMembersResponseError)

export const getGetPartyMembersUrl = (params?: GetPartyMembersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/party/members?${stringifiedParams}` : `/api/party/members`
}

export const getPartyMembers = async (params?: GetPartyMembersParams, options?: RequestInit): Promise<getPartyMembersResponse> => {
  
  return customInstance<getPartyMembersResponse>(getGetPartyMembersUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type setReadyResponse200 = {
  data: ReadyStateResponse
  status: 200
}

export type setReadyResponse400 = {
  data: ErrorResponse
  status: 400
}

export type setReadyResponse404 = {
  data: ErrorResponse
  status: 404
}
    
export type setReadyResponseSuccess = (setReadyResponse200) & {
  headers: Headers;
};
export type setReadyResponseError = (setReadyResponse400 | setReadyResponse404) & {
  headers: Headers;
};

export type setReadyResponse = (setReadyResponseSuccess | setReadyResponseError)

export const getSetReadyUrl = (params: SetReadyParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/party/ready?${stringifiedParams}` : `/api/party/ready`
}

export const setReady = async (params: SetReadyParams, options?: RequestInit): Promise<setReadyResponse> => {
  
  return customInstance<setReadyResponse>(getSetReadyUrl(params),
  {      
    ...options,
    method: 'PATCH'
    
    
  }
);}


