/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  CurrentUserResponse,
  GuestLoginResponse
} from '.././model';


export const getGetCurrentUserResponseMock = (overrideResponse: Partial< CurrentUserResponse > = {}): CurrentUserResponse => ({created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', is_guest: faker.datatype.boolean(), token_expires_at: faker.number.int({min: undefined, max: undefined}), token_expires_in: faker.number.int({min: undefined, max: undefined}), updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z', user_id: faker.string.uuid(), username: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getLoginGuestResponseMock = (overrideResponse: Partial< GuestLoginResponse > = {}): GuestLoginResponse => ({user_id: faker.string.uuid(), username: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})


export const getGetCurrentUserMockHandler = (overrideResponse?: CurrentUserResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CurrentUserResponse> | CurrentUserResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/user', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetCurrentUserResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getLoginGuestMockHandler = (overrideResponse?: GuestLoginResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<GuestLoginResponse> | GuestLoginResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/user/login/guest', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getLoginGuestResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getLogoutUserMockHandler = (overrideResponse?: void | void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void | void> | void | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/user/logout', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getRenameUserMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.patch('*/api/user/rename/:userId', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}
export const getUserMock = () => [
  getGetCurrentUserMockHandler(),
  getLoginGuestMockHandler(),
  getLogoutUserMockHandler(),
  getRenameUserMockHandler()
]
