/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */
import type {
  DeletePickParams,
  ErrorResponse,
  GetPicksParams,
  GetPicksResponse,
  PickMovieParams
} from '../../model';

import { customInstance } from '../../lib/orval-client';

export type getPicksResponse200 = {
  data: GetPicksResponse
  status: 200
}

export type getPicksResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getPicksResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getPicksResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getPicksResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getPicksResponseSuccess = (getPicksResponse200) & {
  headers: Headers;
};
export type getPicksResponseError = (getPicksResponse401 | getPicksResponse403 | getPicksResponse404 | getPicksResponse500) & {
  headers: Headers;
};

export type getPicksResponse = (getPicksResponseSuccess | getPicksResponseError)

export const getGetPicksUrl = (params?: GetPicksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/party/pick?${stringifiedParams}` : `/api/party/pick`
}

export const getPicks = async (params?: GetPicksParams, options?: RequestInit): Promise<getPicksResponse> => {
  
  return customInstance<getPicksResponse>(getGetPicksUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type pickMovieResponse200 = {
  data: void
  status: 200
}

export type pickMovieResponse400 = {
  data: ErrorResponse
  status: 400
}

export type pickMovieResponse401 = {
  data: ErrorResponse
  status: 401
}

export type pickMovieResponse403 = {
  data: ErrorResponse
  status: 403
}

export type pickMovieResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type pickMovieResponseSuccess = (pickMovieResponse200) & {
  headers: Headers;
};
export type pickMovieResponseError = (pickMovieResponse400 | pickMovieResponse401 | pickMovieResponse403 | pickMovieResponse500) & {
  headers: Headers;
};

export type pickMovieResponse = (pickMovieResponseSuccess | pickMovieResponseError)

export const getPickMovieUrl = (params: PickMovieParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/party/pick?${stringifiedParams}` : `/api/party/pick`
}

export const pickMovie = async (params: PickMovieParams, options?: RequestInit): Promise<pickMovieResponse> => {
  
  return customInstance<pickMovieResponse>(getPickMovieUrl(params),
  {      
    ...options,
    method: 'PUT'
    
    
  }
);}


export type deletePickResponse200 = {
  data: void
  status: 200
}

export type deletePickResponse401 = {
  data: ErrorResponse
  status: 401
}

export type deletePickResponse403 = {
  data: ErrorResponse
  status: 403
}

export type deletePickResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type deletePickResponseSuccess = (deletePickResponse200) & {
  headers: Headers;
};
export type deletePickResponseError = (deletePickResponse401 | deletePickResponse403 | deletePickResponse500) & {
  headers: Headers;
};

export type deletePickResponse = (deletePickResponseSuccess | deletePickResponseError)

export const getDeletePickUrl = (params: DeletePickParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/party/pick?${stringifiedParams}` : `/api/party/pick`
}

export const deletePick = async (params: DeletePickParams, options?: RequestInit): Promise<deletePickResponse> => {
  
  return customInstance<deletePickResponse>(getDeletePickUrl(params),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


