/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */
import type {
  ErrorResponse,
  GuestLoginResponse,
  GuestUserRequest,
  RenewJwtResponse
} from '../../model';

import { customInstance } from '../../lib/orval-client';

/**
 * Creates a temporary (oneshot) user. Optionally provide a username (3–32 chars);
otherwise one is generated. On success, the server sets the `id` cookie (httpOnly,
path=/, samesite=Lax, secure). Send it on subsequent requests; protected endpoints use `cookie_auth`.

**Auth**: None.
 * @summary Create a guest user (login as guest).
 */
export type loginGuestResponse201 = {
  data: GuestLoginResponse
  status: 201
}

export type loginGuestResponse400 = {
  data: ErrorResponse
  status: 400
}

export type loginGuestResponse409 = {
  data: ErrorResponse
  status: 409
}

export type loginGuestResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type loginGuestResponseSuccess = (loginGuestResponse201) & {
  headers: Headers;
};
export type loginGuestResponseError = (loginGuestResponse400 | loginGuestResponse409 | loginGuestResponse500) & {
  headers: Headers;
};

export type loginGuestResponse = (loginGuestResponseSuccess | loginGuestResponseError)

export const getLoginGuestUrl = () => {


  

  return `/api/auth/login/guest`
}

export const loginGuest = async (guestUserRequest: GuestUserRequest, options?: RequestInit): Promise<loginGuestResponse> => {
  
  return customInstance<loginGuestResponse>(getLoginGuestUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      guestUserRequest,)
  }
);}


/**
 * @summary Logout: clear `id` cookie. No auth required.
 */
export type logoutUserResponse200 = {
  data: void
  status: 200
}

export type logoutUserResponse204 = {
  data: void
  status: 204
}
    
export type logoutUserResponseSuccess = (logoutUserResponse200 | logoutUserResponse204) & {
  headers: Headers;
};
;

export type logoutUserResponse = (logoutUserResponseSuccess)

export const getLogoutUserUrl = () => {


  

  return `/api/auth/logout`
}

export const logoutUser = async ( options?: RequestInit): Promise<logoutUserResponse> => {
  
  return customInstance<logoutUserResponse>(getLogoutUserUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * Requires existing authentication (cookie or bearer). WebSocket sessions
continue uninterrupted – the new token is only for future HTTP/API calls.
 * @summary Renew the client's JWT by issuing a fresh token with a new expiry.
 */
export type renewJwtResponse200 = {
  data: RenewJwtResponse
  status: 200
}

export type renewJwtResponse401 = {
  data: ErrorResponse
  status: 401
}

export type renewJwtResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type renewJwtResponseSuccess = (renewJwtResponse200) & {
  headers: Headers;
};
export type renewJwtResponseError = (renewJwtResponse401 | renewJwtResponse500) & {
  headers: Headers;
};

export type renewJwtResponse = (renewJwtResponseSuccess | renewJwtResponseError)

export const getRenewJwtUrl = () => {


  

  return `/api/auth/renew`
}

export const renewJwt = async ( options?: RequestInit): Promise<renewJwtResponse> => {
  
  return customInstance<renewJwtResponse>(getRenewJwtUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


