/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */
import type {
  ErrorResponse,
  GuestLoginResponse,
  GuestUserRequest
} from '../../model';

import { customInstance } from '../../lib/orval-client';

/**
 * Exchanges the code for a token and handles user login or account linking.

**Auth**: None (or session user to link account).
 * @summary GitHub OAuth callback handler.
 */
export type callbackGithubResponse302 = {
  data: void
  status: 302
}

export type callbackGithubResponse400 = {
  data: ErrorResponse
  status: 400
}

export type callbackGithubResponse409 = {
  data: ErrorResponse
  status: 409
}

export type callbackGithubResponse500 = {
  data: ErrorResponse
  status: 500
}
    
;
export type callbackGithubResponseError = (callbackGithubResponse302 | callbackGithubResponse400 | callbackGithubResponse409 | callbackGithubResponse500) & {
  headers: Headers;
};

export type callbackGithubResponse = (callbackGithubResponseError)

export const getCallbackGithubUrl = () => {


  

  return `/api/auth/callback/github`
}

export const callbackGithub = async ( options?: RequestInit): Promise<callbackGithubResponse> => {
  
  return customInstance<callbackGithubResponse>(getCallbackGithubUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * **Auth**: None (or session user to link account).
 * @summary Redirect to GitHub OAuth login page.
 */
export type loginGithubResponse302 = {
  data: void
  status: 302
}
    
;
export type loginGithubResponseError = (loginGithubResponse302) & {
  headers: Headers;
};

export type loginGithubResponse = (loginGithubResponseError)

export const getLoginGithubUrl = () => {


  

  return `/api/auth/login/github`
}

export const loginGithub = async ( options?: RequestInit): Promise<loginGithubResponse> => {
  
  return customInstance<loginGithubResponse>(getLoginGithubUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Creates a temporary (oneshot) user. Optionally provide a username (3–32 chars);
otherwise one is generated. On success, the server sets the `id` cookie (httpOnly,
path=/, samesite=Lax, secure). Send it on subsequent requests; protected endpoints use `cookie_auth`.

**Auth**: None.
 * @summary Create a guest user (login as guest).
 */
export type loginGuestResponse201 = {
  data: GuestLoginResponse
  status: 201
}

export type loginGuestResponse400 = {
  data: ErrorResponse
  status: 400
}

export type loginGuestResponse409 = {
  data: ErrorResponse
  status: 409
}

export type loginGuestResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type loginGuestResponseSuccess = (loginGuestResponse201) & {
  headers: Headers;
};
export type loginGuestResponseError = (loginGuestResponse400 | loginGuestResponse409 | loginGuestResponse500) & {
  headers: Headers;
};

export type loginGuestResponse = (loginGuestResponseSuccess | loginGuestResponseError)

export const getLoginGuestUrl = () => {


  

  return `/api/auth/login/guest`
}

export const loginGuest = async (guestUserRequest: GuestUserRequest, options?: RequestInit): Promise<loginGuestResponse> => {
  
  return customInstance<loginGuestResponse>(getLoginGuestUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      guestUserRequest,)
  }
);}


/**
 * @summary Logout: clear `id` cookie. No auth required.
 */
export type logoutUserResponse200 = {
  data: void
  status: 200
}

export type logoutUserResponse204 = {
  data: void
  status: 204
}
    
export type logoutUserResponseSuccess = (logoutUserResponse200 | logoutUserResponse204) & {
  headers: Headers;
};
;

export type logoutUserResponse = (logoutUserResponseSuccess)

export const getLogoutUserUrl = () => {


  

  return `/api/auth/logout`
}

export const logoutUser = async ( options?: RequestInit): Promise<logoutUserResponse> => {
  
  return customInstance<logoutUserResponse>(getLogoutUserUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


