/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  ErrorResponse
} from '.././model';



  
  
  
export type websocketControllerResponse200 = {
  data: void
  status: 200
}

export type websocketControllerResponse400 = {
  data: void
  status: 400
}

export type websocketControllerResponse401 = {
  data: void
  status: 401
}

export type websocketControllerResponse406 = {
  data: void
  status: 406
}

export type websocketControllerResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type websocketControllerResponseSuccess = (websocketControllerResponse200) & {
  headers: Headers;
};
export type websocketControllerResponseError = (websocketControllerResponse400 | websocketControllerResponse401 | websocketControllerResponse406 | websocketControllerResponse500) & {
  headers: Headers;
};

export type websocketControllerResponse = (websocketControllerResponseSuccess | websocketControllerResponseError)

export const getWebsocketControllerUrl = () => {


  

  return `/api/ws`
}

export const websocketController = async ( options?: RequestInit): Promise<websocketControllerResponse> => {
  
  const res = await fetch(getWebsocketControllerUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: websocketControllerResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as websocketControllerResponse
}




export const getWebsocketControllerKey = () => [`/api/ws`] as const;

export type WebsocketControllerQueryResult = NonNullable<Awaited<ReturnType<typeof websocketController>>>

export const useWebsocketController = <TError = Promise<void | void | void | ErrorResponse>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof websocketController>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getWebsocketControllerKey() : null);
  const swrFn = () => websocketController(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
