/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */
import type {
  CurrentUserResponse,
  ErrorResponse,
  GuestLoginResponse,
  GuestUserRequest,
  RenameUserRequest
} from '../../model';


/**
 * Returns the currently authenticated user's profile information
along with JWT token validity details.

**Auth Required**: User must be authenticated with a valid JWT token.
 * @summary Get current user info
 */
export type getCurrentUserResponse200 = {
  data: CurrentUserResponse
  status: 200
}

export type getCurrentUserResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getCurrentUserResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getCurrentUserResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getCurrentUserResponseSuccess = (getCurrentUserResponse200) & {
  headers: Headers;
};
export type getCurrentUserResponseError = (getCurrentUserResponse401 | getCurrentUserResponse404 | getCurrentUserResponse500) & {
  headers: Headers;
};

export type getCurrentUserResponse = (getCurrentUserResponseSuccess | getCurrentUserResponseError)

export const getGetCurrentUserUrl = () => {


  

  return `/api/user`
}

export const getCurrentUser = async ( options?: RequestInit): Promise<getCurrentUserResponse> => {
  
  const res = await fetch(getGetCurrentUserUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getCurrentUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getCurrentUserResponse
}


/**
 * Creates a new temporary (oneshot) user with an auto-generated username.
This user can join parties but will be ephemeral to that party's lifetime.
To become persistent, the user must link an external OAuth account.

This is the entry point for users without an account. Use the returned `user_id`
for subsequent API requests that require authentication.

**Auth**: No authentication required.
 * @summary Create a guest user
 */
export type loginGuestResponse201 = {
  data: GuestLoginResponse
  status: 201
}

export type loginGuestResponse400 = {
  data: ErrorResponse
  status: 400
}

export type loginGuestResponse409 = {
  data: ErrorResponse
  status: 409
}

export type loginGuestResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type loginGuestResponseSuccess = (loginGuestResponse201) & {
  headers: Headers;
};
export type loginGuestResponseError = (loginGuestResponse400 | loginGuestResponse409 | loginGuestResponse500) & {
  headers: Headers;
};

export type loginGuestResponse = (loginGuestResponseSuccess | loginGuestResponseError)

export const getLoginGuestUrl = () => {


  

  return `/api/user/login/guest`
}

export const loginGuest = async (guestUserRequest: GuestUserRequest, options?: RequestInit): Promise<loginGuestResponse> => {
  
  const res = await fetch(getLoginGuestUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      guestUserRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: loginGuestResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as loginGuestResponse
}


/**
 * Clears authentication cookies by setting them to expire.
This effectively logs out the user on the client side.

**Auth**: No authentication required (any user can logout).
 * @summary Logout user
 */
export type logoutUserResponse200 = {
  data: void
  status: 200
}

export type logoutUserResponse204 = {
  data: void
  status: 204
}

export type logoutUserResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type logoutUserResponseSuccess = (logoutUserResponse200 | logoutUserResponse204) & {
  headers: Headers;
};
export type logoutUserResponseError = (logoutUserResponse500) & {
  headers: Headers;
};

export type logoutUserResponse = (logoutUserResponseSuccess | logoutUserResponseError)

export const getLogoutUserUrl = () => {


  

  return `/api/user/logout`
}

export const logoutUser = async ( options?: RequestInit): Promise<logoutUserResponse> => {
  
  const res = await fetch(getLogoutUserUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: logoutUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as logoutUserResponse
}


/**
 * Updates the username for a user. Username can be 3-32 characters.

**Auth Required**: User can only rename their own account (user_id must match JWT token).


 * @summary Rename a user
 */
export type renameUserResponse200 = {
  data: void
  status: 200
}

export type renameUserResponse400 = {
  data: ErrorResponse
  status: 400
}

export type renameUserResponse401 = {
  data: void
  status: 401
}

export type renameUserResponse403 = {
  data: void
  status: 403
}

export type renameUserResponse404 = {
  data: void
  status: 404
}

export type renameUserResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type renameUserResponseSuccess = (renameUserResponse200) & {
  headers: Headers;
};
export type renameUserResponseError = (renameUserResponse400 | renameUserResponse401 | renameUserResponse403 | renameUserResponse404 | renameUserResponse500) & {
  headers: Headers;
};

export type renameUserResponse = (renameUserResponseSuccess | renameUserResponseError)

export const getRenameUserUrl = (userId: string,) => {


  

  return `/api/user/rename/${userId}`
}

export const renameUser = async (userId: string,
    renameUserRequest: RenameUserRequest, options?: RequestInit): Promise<renameUserResponse> => {
  
  const res = await fetch(getRenameUserUrl(userId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      renameUserRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: renameUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as renameUserResponse
}


