/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */
import type {
  CurrentUserResponse,
  ErrorResponse,
  GuestLoginResponse,
  GuestUserRequest,
  RenameUserRequest,
  UpdateTasteRequest,
  UpdateUserPreferencesRequest,
  UserPreferencesResponse
} from '../../model';

import customInstance from '../../lib/orval-client';

/**
 * @summary Current user profile (cookie-authenticated).
 */
export type getCurrentUserResponse200 = {
  data: CurrentUserResponse
  status: 200
}

export type getCurrentUserResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getCurrentUserResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getCurrentUserResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getCurrentUserResponseSuccess = (getCurrentUserResponse200) & {
  headers: Headers;
};
export type getCurrentUserResponseError = (getCurrentUserResponse401 | getCurrentUserResponse404 | getCurrentUserResponse500) & {
  headers: Headers;
};

export type getCurrentUserResponse = (getCurrentUserResponseSuccess | getCurrentUserResponseError)

export const getGetCurrentUserUrl = () => {


  

  return `/api/user`
}

export const getCurrentUser = async ( options?: RequestInit): Promise<getCurrentUserResponse> => {
  
  return customInstance<getCurrentUserResponse>(getGetCurrentUserUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Like or unlike a movie (global taste). Movie must exist.
 */
export type updateTasteResponse200 = {
  data: void
  status: 200
}

export type updateTasteResponse401 = {
  data: ErrorResponse
  status: 401
}

export type updateTasteResponse404 = {
  data: ErrorResponse
  status: 404
}

export type updateTasteResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type updateTasteResponseSuccess = (updateTasteResponse200) & {
  headers: Headers;
};
export type updateTasteResponseError = (updateTasteResponse401 | updateTasteResponse404 | updateTasteResponse500) & {
  headers: Headers;
};

export type updateTasteResponse = (updateTasteResponseSuccess | updateTasteResponseError)

export const getUpdateTasteUrl = (movieId: number,) => {


  

  return `/api/user/like/${movieId}`
}

export const updateTaste = async (movieId: number,
    updateTasteRequest: UpdateTasteRequest, options?: RequestInit): Promise<updateTasteResponse> => {
  
  return customInstance<updateTasteResponse>(getUpdateTasteUrl(movieId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateTasteRequest,)
  }
);}


/**
 * Creates a temporary (oneshot) user. Optionally provide a username (3–32 chars);
otherwise one is generated. On success, the server sets the `id` cookie (httpOnly,
path=/, samesite=Lax, secure). Send it on subsequent requests; protected endpoints use `cookie_auth`.

**Auth**: None.
 * @summary Create a guest user (login as guest).
 */
export type loginGuestResponse201 = {
  data: GuestLoginResponse
  status: 201
}

export type loginGuestResponse400 = {
  data: ErrorResponse
  status: 400
}

export type loginGuestResponse409 = {
  data: ErrorResponse
  status: 409
}

export type loginGuestResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type loginGuestResponseSuccess = (loginGuestResponse201) & {
  headers: Headers;
};
export type loginGuestResponseError = (loginGuestResponse400 | loginGuestResponse409 | loginGuestResponse500) & {
  headers: Headers;
};

export type loginGuestResponse = (loginGuestResponseSuccess | loginGuestResponseError)

export const getLoginGuestUrl = () => {


  

  return `/api/user/login/guest`
}

export const loginGuest = async (guestUserRequest: GuestUserRequest, options?: RequestInit): Promise<loginGuestResponse> => {
  
  return customInstance<loginGuestResponse>(getLoginGuestUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      guestUserRequest,)
  }
);}


/**
 * @summary Logout: clear `id` cookie. No auth required.
 */
export type logoutUserResponse200 = {
  data: void
  status: 200
}

export type logoutUserResponse204 = {
  data: void
  status: 204
}
    
export type logoutUserResponseSuccess = (logoutUserResponse200 | logoutUserResponse204) & {
  headers: Headers;
};
;

export type logoutUserResponse = (logoutUserResponseSuccess)

export const getLogoutUserUrl = () => {


  

  return `/api/user/logout`
}

export const logoutUser = async ( options?: RequestInit): Promise<logoutUserResponse> => {
  
  return customInstance<logoutUserResponse>(getLogoutUserUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * @summary Current user's preferences (genres, year, etc.).
 */
export type getUserPreferencesResponse200 = {
  data: UserPreferencesResponse
  status: 200
}

export type getUserPreferencesResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getUserPreferencesResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getUserPreferencesResponseSuccess = (getUserPreferencesResponse200) & {
  headers: Headers;
};
export type getUserPreferencesResponseError = (getUserPreferencesResponse401 | getUserPreferencesResponse500) & {
  headers: Headers;
};

export type getUserPreferencesResponse = (getUserPreferencesResponseSuccess | getUserPreferencesResponseError)

export const getGetUserPreferencesUrl = () => {


  

  return `/api/user/pref`
}

export const getUserPreferences = async ( options?: RequestInit): Promise<getUserPreferencesResponse> => {
  
  return customInstance<getUserPreferencesResponse>(getGetUserPreferencesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Update current user's preferences. Invalid genre names return 400.
 */
export type editUserPreferencesResponse200 = {
  data: UserPreferencesResponse
  status: 200
}

export type editUserPreferencesResponse400 = {
  data: ErrorResponse
  status: 400
}

export type editUserPreferencesResponse401 = {
  data: ErrorResponse
  status: 401
}

export type editUserPreferencesResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type editUserPreferencesResponseSuccess = (editUserPreferencesResponse200) & {
  headers: Headers;
};
export type editUserPreferencesResponseError = (editUserPreferencesResponse400 | editUserPreferencesResponse401 | editUserPreferencesResponse500) & {
  headers: Headers;
};

export type editUserPreferencesResponse = (editUserPreferencesResponseSuccess | editUserPreferencesResponseError)

export const getEditUserPreferencesUrl = () => {


  

  return `/api/user/pref`
}

export const editUserPreferences = async (updateUserPreferencesRequest: UpdateUserPreferencesRequest, options?: RequestInit): Promise<editUserPreferencesResponse> => {
  
  return customInstance<editUserPreferencesResponse>(getEditUserPreferencesUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateUserPreferencesRequest,)
  }
);}


/**
 * Username must be 3–32 characters. Caller must match `user_id` (cookie).
 * @summary Rename the authenticated user.
 */
export type renameUserResponse200 = {
  data: void
  status: 200
}

export type renameUserResponse400 = {
  data: ErrorResponse
  status: 400
}

export type renameUserResponse401 = {
  data: ErrorResponse
  status: 401
}

export type renameUserResponse403 = {
  data: void
  status: 403
}

export type renameUserResponse404 = {
  data: void
  status: 404
}

export type renameUserResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type renameUserResponseSuccess = (renameUserResponse200) & {
  headers: Headers;
};
export type renameUserResponseError = (renameUserResponse400 | renameUserResponse401 | renameUserResponse403 | renameUserResponse404 | renameUserResponse500) & {
  headers: Headers;
};

export type renameUserResponse = (renameUserResponseSuccess | renameUserResponseError)

export const getRenameUserUrl = (userId: string,) => {


  

  return `/api/user/rename/${userId}`
}

export const renameUser = async (userId: string,
    renameUserRequest: RenameUserRequest, options?: RequestInit): Promise<renameUserResponse> => {
  
  return customInstance<renameUserResponse>(getRenameUserUrl(userId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      renameUserRequest,)
  }
);}


