/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */
import type {
  CurrentUserResponse,
  ErrorResponse,
  RenameUserParams,
  UpdateTasteParams,
  UpdateUserPreferencesRequest,
  UserPreferencesResponse
} from '../../model';

import { customInstance } from '../../lib/orval-client';

/**
 * @summary Current user profile (cookie-authenticated).
 */
export type getCurrentUserResponse200 = {
  data: CurrentUserResponse
  status: 200
}

export type getCurrentUserResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getCurrentUserResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getCurrentUserResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getCurrentUserResponseSuccess = (getCurrentUserResponse200) & {
  headers: Headers;
};
export type getCurrentUserResponseError = (getCurrentUserResponse401 | getCurrentUserResponse404 | getCurrentUserResponse500) & {
  headers: Headers;
};

export type getCurrentUserResponse = (getCurrentUserResponseSuccess | getCurrentUserResponseError)

export const getGetCurrentUserUrl = () => {


  

  return `/api/user`
}

export const getCurrentUser = async ( options?: RequestInit): Promise<getCurrentUserResponse> => {
  
  return customInstance<getCurrentUserResponse>(getGetCurrentUserUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Current user's preferences (genres, year, etc.).
 */
export type getUserPreferencesResponse200 = {
  data: UserPreferencesResponse
  status: 200
}

export type getUserPreferencesResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getUserPreferencesResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getUserPreferencesResponseSuccess = (getUserPreferencesResponse200) & {
  headers: Headers;
};
export type getUserPreferencesResponseError = (getUserPreferencesResponse401 | getUserPreferencesResponse500) & {
  headers: Headers;
};

export type getUserPreferencesResponse = (getUserPreferencesResponseSuccess | getUserPreferencesResponseError)

export const getGetUserPreferencesUrl = () => {


  

  return `/api/user/preferences`
}

export const getUserPreferences = async ( options?: RequestInit): Promise<getUserPreferencesResponse> => {
  
  return customInstance<getUserPreferencesResponse>(getGetUserPreferencesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Update current user's preferences. Invalid genre names return 400.
 */
export type editUserPreferencesResponse200 = {
  data: UserPreferencesResponse
  status: 200
}

export type editUserPreferencesResponse400 = {
  data: ErrorResponse
  status: 400
}

export type editUserPreferencesResponse401 = {
  data: ErrorResponse
  status: 401
}

export type editUserPreferencesResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type editUserPreferencesResponseSuccess = (editUserPreferencesResponse200) & {
  headers: Headers;
};
export type editUserPreferencesResponseError = (editUserPreferencesResponse400 | editUserPreferencesResponse401 | editUserPreferencesResponse500) & {
  headers: Headers;
};

export type editUserPreferencesResponse = (editUserPreferencesResponseSuccess | editUserPreferencesResponseError)

export const getEditUserPreferencesUrl = () => {


  

  return `/api/user/preferences`
}

export const editUserPreferences = async (updateUserPreferencesRequest: UpdateUserPreferencesRequest, options?: RequestInit): Promise<editUserPreferencesResponse> => {
  
  return customInstance<editUserPreferencesResponse>(getEditUserPreferencesUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateUserPreferencesRequest,)
  }
);}


/**
 * Username must be 3–32 characters. Caller must match `user_id` (cookie).
 * @summary Rename the authenticated user.
 */
export type renameUserResponse200 = {
  data: void
  status: 200
}

export type renameUserResponse400 = {
  data: ErrorResponse
  status: 400
}

export type renameUserResponse401 = {
  data: ErrorResponse
  status: 401
}

export type renameUserResponse403 = {
  data: void
  status: 403
}

export type renameUserResponse404 = {
  data: void
  status: 404
}

export type renameUserResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type renameUserResponseSuccess = (renameUserResponse200) & {
  headers: Headers;
};
export type renameUserResponseError = (renameUserResponse400 | renameUserResponse401 | renameUserResponse403 | renameUserResponse404 | renameUserResponse500) & {
  headers: Headers;
};

export type renameUserResponse = (renameUserResponseSuccess | renameUserResponseError)

export const getRenameUserUrl = (params: RenameUserParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/user/rename?${stringifiedParams}` : `/api/user/rename`
}

export const renameUser = async (params: RenameUserParams, options?: RequestInit): Promise<renameUserResponse> => {
  
  return customInstance<renameUserResponse>(getRenameUserUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * @summary Update movie taste (liked status and rating).
 */
export type updateTasteResponse200 = {
  data: void
  status: 200
}

export type updateTasteResponse401 = {
  data: ErrorResponse
  status: 401
}

export type updateTasteResponse404 = {
  data: ErrorResponse
  status: 404
}

export type updateTasteResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type updateTasteResponseSuccess = (updateTasteResponse200) & {
  headers: Headers;
};
export type updateTasteResponseError = (updateTasteResponse401 | updateTasteResponse404 | updateTasteResponse500) & {
  headers: Headers;
};

export type updateTasteResponse = (updateTasteResponseSuccess | updateTasteResponseError)

export const getUpdateTasteUrl = (params: UpdateTasteParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/user/taste?${stringifiedParams}` : `/api/user/taste`
}

export const updateTaste = async (params: UpdateTasteParams, options?: RequestInit): Promise<updateTasteResponse> => {
  
  return customInstance<updateTasteResponse>(getUpdateTasteUrl(params),
  {      
    ...options,
    method: 'PUT'
    
    
  }
);}


