/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */
import type {
  CreatePartyResponse,
  ErrorResponse,
  GetPicksResponse,
  GetVoteResponse,
  KickMemberRequest,
  PartyMembersResponse,
  PartyResponse,
  ReadyStateResponse,
  SetReadyRequest,
  TransferLeadershipRequest,
  UpdateTasteRequest,
  VoteMovieRequest,
  VoteMovieResponse
} from '@/model';

import { customInstance } from '@/lib/orval-client';

export type getMyPartyResponse200 = {
  data: PartyResponse
  status: 200
}

export type getMyPartyResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getMyPartyResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getMyPartyResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getMyPartyResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getMyPartyResponseSuccess = (getMyPartyResponse200) & {
  headers: Headers;
};
export type getMyPartyResponseError = (getMyPartyResponse401 | getMyPartyResponse403 | getMyPartyResponse404 | getMyPartyResponse500) & {
  headers: Headers;
};

export type getMyPartyResponse = (getMyPartyResponseSuccess | getMyPartyResponseError)

export const getGetMyPartyUrl = () => {


  

  return `/api/party`
}

export const getMyParty = async ( options?: RequestInit): Promise<getMyPartyResponse> => {
  
  return customInstance<getMyPartyResponse>(getGetMyPartyUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type createPartyResponse201 = {
  data: CreatePartyResponse
  status: 201
}

export type createPartyResponse401 = {
  data: ErrorResponse
  status: 401
}

export type createPartyResponse403 = {
  data: ErrorResponse
  status: 403
}

export type createPartyResponse404 = {
  data: ErrorResponse
  status: 404
}

export type createPartyResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type createPartyResponseSuccess = (createPartyResponse201) & {
  headers: Headers;
};
export type createPartyResponseError = (createPartyResponse401 | createPartyResponse403 | createPartyResponse404 | createPartyResponse500) & {
  headers: Headers;
};

export type createPartyResponse = (createPartyResponseSuccess | createPartyResponseError)

export const getCreatePartyUrl = () => {


  

  return `/api/party`
}

export const createParty = async ( options?: RequestInit): Promise<createPartyResponse> => {
  
  return customInstance<createPartyResponse>(getCreatePartyUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


export type joinPartyResponse200 = {
  data: CreatePartyResponse
  status: 200
}

export type joinPartyResponse400 = {
  data: ErrorResponse
  status: 400
}

export type joinPartyResponse401 = {
  data: ErrorResponse
  status: 401
}

export type joinPartyResponse404 = {
  data: ErrorResponse
  status: 404
}

export type joinPartyResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type joinPartyResponseSuccess = (joinPartyResponse200) & {
  headers: Headers;
};
export type joinPartyResponseError = (joinPartyResponse400 | joinPartyResponse401 | joinPartyResponse404 | joinPartyResponse500) & {
  headers: Headers;
};

export type joinPartyResponse = (joinPartyResponseSuccess | joinPartyResponseError)

export const getJoinPartyUrl = (code: string,) => {


  

  return `/api/party/join/${code}`
}

export const joinParty = async (code: string, options?: RequestInit): Promise<joinPartyResponse> => {
  
  return customInstance<joinPartyResponse>(getJoinPartyUrl(code),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


export type getPartyResponse200 = {
  data: PartyResponse
  status: 200
}

export type getPartyResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getPartyResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getPartyResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getPartyResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getPartyResponseSuccess = (getPartyResponse200) & {
  headers: Headers;
};
export type getPartyResponseError = (getPartyResponse401 | getPartyResponse403 | getPartyResponse404 | getPartyResponse500) & {
  headers: Headers;
};

export type getPartyResponse = (getPartyResponseSuccess | getPartyResponseError)

export const getGetPartyUrl = (partyId: string,) => {


  

  return `/api/party/${partyId}`
}

export const getParty = async (partyId: string, options?: RequestInit): Promise<getPartyResponse> => {
  
  return customInstance<getPartyResponse>(getGetPartyUrl(partyId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type advancePhaseResponse200 = {
  data: void
  status: 200
}

export type advancePhaseResponse400 = {
  data: ErrorResponse
  status: 400
}

export type advancePhaseResponse401 = {
  data: ErrorResponse
  status: 401
}

export type advancePhaseResponse403 = {
  data: ErrorResponse
  status: 403
}

export type advancePhaseResponse404 = {
  data: ErrorResponse
  status: 404
}

export type advancePhaseResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type advancePhaseResponseSuccess = (advancePhaseResponse200) & {
  headers: Headers;
};
export type advancePhaseResponseError = (advancePhaseResponse400 | advancePhaseResponse401 | advancePhaseResponse403 | advancePhaseResponse404 | advancePhaseResponse500) & {
  headers: Headers;
};

export type advancePhaseResponse = (advancePhaseResponseSuccess | advancePhaseResponseError)

export const getAdvancePhaseUrl = (partyId: string,) => {


  

  return `/api/party/${partyId}/advance`
}

export const advancePhase = async (partyId: string, options?: RequestInit): Promise<advancePhaseResponse> => {
  
  return customInstance<advancePhaseResponse>(getAdvancePhaseUrl(partyId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * @summary Disband party (leader only).
 */
export type disbandPartyResponse200 = {
  data: void
  status: 200
}

export type disbandPartyResponse401 = {
  data: ErrorResponse
  status: 401
}

export type disbandPartyResponse403 = {
  data: ErrorResponse
  status: 403
}

export type disbandPartyResponse404 = {
  data: void
  status: 404
}

export type disbandPartyResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type disbandPartyResponseSuccess = (disbandPartyResponse200) & {
  headers: Headers;
};
export type disbandPartyResponseError = (disbandPartyResponse401 | disbandPartyResponse403 | disbandPartyResponse404 | disbandPartyResponse500) & {
  headers: Headers;
};

export type disbandPartyResponse = (disbandPartyResponseSuccess | disbandPartyResponseError)

export const getDisbandPartyUrl = (partyId: string,) => {


  

  return `/api/party/${partyId}/disband`
}

export const disbandParty = async (partyId: string, options?: RequestInit): Promise<disbandPartyResponse> => {
  
  return customInstance<disbandPartyResponse>(getDisbandPartyUrl(partyId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * @summary Kick a member (leader only).
 */
export type kickMemberResponse200 = {
  data: void
  status: 200
}

export type kickMemberResponse401 = {
  data: ErrorResponse
  status: 401
}

export type kickMemberResponse403 = {
  data: ErrorResponse
  status: 403
}

export type kickMemberResponse404 = {
  data: ErrorResponse
  status: 404
}

export type kickMemberResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type kickMemberResponseSuccess = (kickMemberResponse200) & {
  headers: Headers;
};
export type kickMemberResponseError = (kickMemberResponse401 | kickMemberResponse403 | kickMemberResponse404 | kickMemberResponse500) & {
  headers: Headers;
};

export type kickMemberResponse = (kickMemberResponseSuccess | kickMemberResponseError)

export const getKickMemberUrl = (partyId: string,) => {


  

  return `/api/party/${partyId}/kick`
}

export const kickMember = async (partyId: string,
    kickMemberRequest: KickMemberRequest, options?: RequestInit): Promise<kickMemberResponse> => {
  
  return customInstance<kickMemberResponse>(getKickMemberUrl(partyId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      kickMemberRequest,)
  }
);}


/**
 * @summary Leave the party. Leader leaves → transfer to oldest member; no members left → disband.
 */
export type leavePartyResponse200 = {
  data: void
  status: 200
}

export type leavePartyResponse400 = {
  data: ErrorResponse
  status: 400
}

export type leavePartyResponse401 = {
  data: ErrorResponse
  status: 401
}

export type leavePartyResponse404 = {
  data: void
  status: 404
}

export type leavePartyResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type leavePartyResponseSuccess = (leavePartyResponse200) & {
  headers: Headers;
};
export type leavePartyResponseError = (leavePartyResponse400 | leavePartyResponse401 | leavePartyResponse404 | leavePartyResponse500) & {
  headers: Headers;
};

export type leavePartyResponse = (leavePartyResponseSuccess | leavePartyResponseError)

export const getLeavePartyUrl = (partyId: string,) => {


  

  return `/api/party/${partyId}/leave`
}

export const leaveParty = async (partyId: string, options?: RequestInit): Promise<leavePartyResponse> => {
  
  return customInstance<leavePartyResponse>(getLeavePartyUrl(partyId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


export type getPartyMembersResponse200 = {
  data: PartyMembersResponse
  status: 200
}

export type getPartyMembersResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getPartyMembersResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getPartyMembersResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getPartyMembersResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getPartyMembersResponseSuccess = (getPartyMembersResponse200) & {
  headers: Headers;
};
export type getPartyMembersResponseError = (getPartyMembersResponse401 | getPartyMembersResponse403 | getPartyMembersResponse404 | getPartyMembersResponse500) & {
  headers: Headers;
};

export type getPartyMembersResponse = (getPartyMembersResponseSuccess | getPartyMembersResponseError)

export const getGetPartyMembersUrl = (partyId: string,) => {


  

  return `/api/party/${partyId}/members`
}

export const getPartyMembers = async (partyId: string, options?: RequestInit): Promise<getPartyMembersResponse> => {
  
  return customInstance<getPartyMembersResponse>(getGetPartyMembersUrl(partyId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type pickMovieResponse200 = {
  data: void
  status: 200
}

export type pickMovieResponse400 = {
  data: ErrorResponse
  status: 400
}

export type pickMovieResponse401 = {
  data: ErrorResponse
  status: 401
}

export type pickMovieResponse403 = {
  data: ErrorResponse
  status: 403
}

export type pickMovieResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type pickMovieResponseSuccess = (pickMovieResponse200) & {
  headers: Headers;
};
export type pickMovieResponseError = (pickMovieResponse400 | pickMovieResponse401 | pickMovieResponse403 | pickMovieResponse500) & {
  headers: Headers;
};

export type pickMovieResponse = (pickMovieResponseSuccess | pickMovieResponseError)

export const getPickMovieUrl = (partyId: string,
    movieId: number,) => {


  

  return `/api/party/${partyId}/pick/${movieId}`
}

export const pickMovie = async (partyId: string,
    movieId: number,
    updateTasteRequest: UpdateTasteRequest, options?: RequestInit): Promise<pickMovieResponse> => {
  
  return customInstance<pickMovieResponse>(getPickMovieUrl(partyId,movieId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateTasteRequest,)
  }
);}


export type deletePickResponse200 = {
  data: void
  status: 200
}

export type deletePickResponse401 = {
  data: ErrorResponse
  status: 401
}

export type deletePickResponse403 = {
  data: ErrorResponse
  status: 403
}

export type deletePickResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type deletePickResponseSuccess = (deletePickResponse200) & {
  headers: Headers;
};
export type deletePickResponseError = (deletePickResponse401 | deletePickResponse403 | deletePickResponse500) & {
  headers: Headers;
};

export type deletePickResponse = (deletePickResponseSuccess | deletePickResponseError)

export const getDeletePickUrl = (partyId: string,
    movieId: number,) => {


  

  return `/api/party/${partyId}/pick/${movieId}`
}

export const deletePick = async (partyId: string,
    movieId: number, options?: RequestInit): Promise<deletePickResponse> => {
  
  return customInstance<deletePickResponse>(getDeletePickUrl(partyId,movieId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


export type getPicksResponse200 = {
  data: GetPicksResponse
  status: 200
}

export type getPicksResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getPicksResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getPicksResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getPicksResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getPicksResponseSuccess = (getPicksResponse200) & {
  headers: Headers;
};
export type getPicksResponseError = (getPicksResponse401 | getPicksResponse403 | getPicksResponse404 | getPicksResponse500) & {
  headers: Headers;
};

export type getPicksResponse = (getPicksResponseSuccess | getPicksResponseError)

export const getGetPicksUrl = (partyId: string,) => {


  

  return `/api/party/${partyId}/picks`
}

export const getPicks = async (partyId: string, options?: RequestInit): Promise<getPicksResponse> => {
  
  return customInstance<getPicksResponse>(getGetPicksUrl(partyId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type setReadyResponse200 = {
  data: ReadyStateResponse
  status: 200
}

export type setReadyResponse400 = {
  data: ErrorResponse
  status: 400
}

export type setReadyResponse401 = {
  data: ErrorResponse
  status: 401
}

export type setReadyResponse404 = {
  data: ErrorResponse
  status: 404
}

export type setReadyResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type setReadyResponseSuccess = (setReadyResponse200) & {
  headers: Headers;
};
export type setReadyResponseError = (setReadyResponse400 | setReadyResponse401 | setReadyResponse404 | setReadyResponse500) & {
  headers: Headers;
};

export type setReadyResponse = (setReadyResponseSuccess | setReadyResponseError)

export const getSetReadyUrl = (partyId: string,) => {


  

  return `/api/party/${partyId}/ready`
}

export const setReady = async (partyId: string,
    setReadyRequest: SetReadyRequest, options?: RequestInit): Promise<setReadyResponse> => {
  
  return customInstance<setReadyResponse>(getSetReadyUrl(partyId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      setReadyRequest,)
  }
);}


/**
 * @summary Transfer leadership (leader only). New leader must be a party member.
 */
export type transferLeadershipResponse200 = {
  data: void
  status: 200
}

export type transferLeadershipResponse400 = {
  data: ErrorResponse
  status: 400
}

export type transferLeadershipResponse401 = {
  data: ErrorResponse
  status: 401
}

export type transferLeadershipResponse403 = {
  data: ErrorResponse
  status: 403
}

export type transferLeadershipResponse404 = {
  data: ErrorResponse
  status: 404
}

export type transferLeadershipResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type transferLeadershipResponseSuccess = (transferLeadershipResponse200) & {
  headers: Headers;
};
export type transferLeadershipResponseError = (transferLeadershipResponse400 | transferLeadershipResponse401 | transferLeadershipResponse403 | transferLeadershipResponse404 | transferLeadershipResponse500) & {
  headers: Headers;
};

export type transferLeadershipResponse = (transferLeadershipResponseSuccess | transferLeadershipResponseError)

export const getTransferLeadershipUrl = (partyId: string,) => {


  

  return `/api/party/${partyId}/transfer-leadership`
}

export const transferLeadership = async (partyId: string,
    transferLeadershipRequest: TransferLeadershipRequest, options?: RequestInit): Promise<transferLeadershipResponse> => {
  
  return customInstance<transferLeadershipResponse>(getTransferLeadershipUrl(partyId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      transferLeadershipRequest,)
  }
);}


export type getVoteResponse200 = {
  data: GetVoteResponse
  status: 200
}

export type getVoteResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getVoteResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getVoteResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getVoteResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getVoteResponseSuccess = (getVoteResponse200) & {
  headers: Headers;
};
export type getVoteResponseError = (getVoteResponse401 | getVoteResponse403 | getVoteResponse404 | getVoteResponse500) & {
  headers: Headers;
};

export type getVoteResponse = (getVoteResponseSuccess | getVoteResponseError)

export const getGetVoteUrl = (partyId: string,) => {


  

  return `/api/party/${partyId}/vote`
}

export const getVote = async (partyId: string, options?: RequestInit): Promise<getVoteResponse> => {
  
  return customInstance<getVoteResponse>(getGetVoteUrl(partyId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type voteMovieResponse200 = {
  data: VoteMovieResponse
  status: 200
}

export type voteMovieResponse401 = {
  data: ErrorResponse
  status: 401
}

export type voteMovieResponse403 = {
  data: ErrorResponse
  status: 403
}

export type voteMovieResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type voteMovieResponseSuccess = (voteMovieResponse200) & {
  headers: Headers;
};
export type voteMovieResponseError = (voteMovieResponse401 | voteMovieResponse403 | voteMovieResponse500) & {
  headers: Headers;
};

export type voteMovieResponse = (voteMovieResponseSuccess | voteMovieResponseError)

export const getVoteMovieUrl = (partyId: string,
    movieId: number,) => {


  

  return `/api/party/${partyId}/vote/${movieId}`
}

export const voteMovie = async (partyId: string,
    movieId: number,
    voteMovieRequest: VoteMovieRequest, options?: RequestInit): Promise<voteMovieResponse> => {
  
  return customInstance<voteMovieResponse>(getVoteMovieUrl(partyId,movieId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      voteMovieRequest,)
  }
);}


