/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-server
 * OpenAPI spec version: 0.1.0
 */
import type {
  CreatePartyResponse,
  ErrorResponse,
  GetPartyParams,
  PartyResponse
} from '../../model';

import { customInstance } from '../../lib/orval-client';

export type getPartyResponse200 = {
  data: PartyResponse
  status: 200
}

export type getPartyResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getPartyResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getPartyResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getPartyResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getPartyResponseSuccess = (getPartyResponse200) & {
  headers: Headers;
};
export type getPartyResponseError = (getPartyResponse401 | getPartyResponse403 | getPartyResponse404 | getPartyResponse500) & {
  headers: Headers;
};

export type getPartyResponse = (getPartyResponseSuccess | getPartyResponseError)

export const getGetPartyUrl = (params?: GetPartyParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/party?${stringifiedParams}` : `/api/party`
}

export const getParty = async (params?: GetPartyParams, options?: RequestInit): Promise<getPartyResponse> => {
  
  return customInstance<getPartyResponse>(getGetPartyUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type createPartyResponse201 = {
  data: CreatePartyResponse
  status: 201
}

export type createPartyResponse401 = {
  data: ErrorResponse
  status: 401
}

export type createPartyResponse403 = {
  data: ErrorResponse
  status: 403
}

export type createPartyResponse404 = {
  data: ErrorResponse
  status: 404
}

export type createPartyResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type createPartyResponseSuccess = (createPartyResponse201) & {
  headers: Headers;
};
export type createPartyResponseError = (createPartyResponse401 | createPartyResponse403 | createPartyResponse404 | createPartyResponse500) & {
  headers: Headers;
};

export type createPartyResponse = (createPartyResponseSuccess | createPartyResponseError)

export const getCreatePartyUrl = () => {


  

  return `/api/party`
}

export const createParty = async ( options?: RequestInit): Promise<createPartyResponse> => {
  
  return customInstance<createPartyResponse>(getCreatePartyUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


