/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */
import type {
  CreatePartyResponse,
  ErrorResponse,
  KickMemberRequest,
  NewRoundResponse,
  PartyMembersResponse,
  PartyResponse,
  PhaseAdvanceResponse,
  SetReadyRequest,
  TransferLeadershipRequest
} from '../../model';


export type createPartyResponse201 = {
  data: CreatePartyResponse
  status: 201
}

export type createPartyResponse401 = {
  data: ErrorResponse
  status: 401
}

export type createPartyResponse404 = {
  data: ErrorResponse
  status: 404
}

export type createPartyResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type createPartyResponseSuccess = (createPartyResponse201) & {
  headers: Headers;
};
export type createPartyResponseError = (createPartyResponse401 | createPartyResponse404 | createPartyResponse500) & {
  headers: Headers;
};

export type createPartyResponse = (createPartyResponseSuccess | createPartyResponseError)

export const getCreatePartyUrl = () => {


  

  return `/api/party`
}

export const createParty = async ( options?: RequestInit): Promise<createPartyResponse> => {
  
  const res = await fetch(getCreatePartyUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createPartyResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createPartyResponse
}


export type joinPartyResponse200 = {
  data: CreatePartyResponse
  status: 200
}

export type joinPartyResponse400 = {
  data: ErrorResponse
  status: 400
}

export type joinPartyResponse401 = {
  data: ErrorResponse
  status: 401
}

export type joinPartyResponse404 = {
  data: ErrorResponse
  status: 404
}

export type joinPartyResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type joinPartyResponseSuccess = (joinPartyResponse200) & {
  headers: Headers;
};
export type joinPartyResponseError = (joinPartyResponse400 | joinPartyResponse401 | joinPartyResponse404 | joinPartyResponse500) & {
  headers: Headers;
};

export type joinPartyResponse = (joinPartyResponseSuccess | joinPartyResponseError)

export const getJoinPartyUrl = (code: string,) => {


  

  return `/api/party/join/${code}`
}

export const joinParty = async (code: string, options?: RequestInit): Promise<joinPartyResponse> => {
  
  const res = await fetch(getJoinPartyUrl(code),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: joinPartyResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as joinPartyResponse
}


export type getPartyResponse200 = {
  data: PartyResponse
  status: 200
}

export type getPartyResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getPartyResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getPartyResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getPartyResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getPartyResponseSuccess = (getPartyResponse200) & {
  headers: Headers;
};
export type getPartyResponseError = (getPartyResponse401 | getPartyResponse403 | getPartyResponse404 | getPartyResponse500) & {
  headers: Headers;
};

export type getPartyResponse = (getPartyResponseSuccess | getPartyResponseError)

export const getGetPartyUrl = (partyId: string,) => {


  

  return `/api/party/${partyId}`
}

export const getParty = async (partyId: string, options?: RequestInit): Promise<getPartyResponse> => {
  
  const res = await fetch(getGetPartyUrl(partyId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getPartyResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getPartyResponse
}


export type advancePhaseResponse200 = {
  data: PhaseAdvanceResponse
  status: 200
}

export type advancePhaseResponse400 = {
  data: ErrorResponse
  status: 400
}

export type advancePhaseResponse401 = {
  data: ErrorResponse
  status: 401
}

export type advancePhaseResponse403 = {
  data: ErrorResponse
  status: 403
}

export type advancePhaseResponse404 = {
  data: ErrorResponse
  status: 404
}

export type advancePhaseResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type advancePhaseResponseSuccess = (advancePhaseResponse200) & {
  headers: Headers;
};
export type advancePhaseResponseError = (advancePhaseResponse400 | advancePhaseResponse401 | advancePhaseResponse403 | advancePhaseResponse404 | advancePhaseResponse500) & {
  headers: Headers;
};

export type advancePhaseResponse = (advancePhaseResponseSuccess | advancePhaseResponseError)

export const getAdvancePhaseUrl = (partyId: string,) => {


  

  return `/api/party/${partyId}/advance`
}

export const advancePhase = async (partyId: string, options?: RequestInit): Promise<advancePhaseResponse> => {
  
  const res = await fetch(getAdvancePhaseUrl(partyId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: advancePhaseResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as advancePhaseResponse
}


/**
 * Disbands the party completely. Only the party leader can disband.
This sets the party state to Disbanded and removes the join code.

**Auth**: Only the party leader can disband the party.
 * @summary Disband party
 */
export type disbandPartyResponse200 = {
  data: void
  status: 200
}

export type disbandPartyResponse401 = {
  data: ErrorResponse
  status: 401
}

export type disbandPartyResponse403 = {
  data: ErrorResponse
  status: 403
}

export type disbandPartyResponse404 = {
  data: ErrorResponse
  status: 404
}

export type disbandPartyResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type disbandPartyResponseSuccess = (disbandPartyResponse200) & {
  headers: Headers;
};
export type disbandPartyResponseError = (disbandPartyResponse401 | disbandPartyResponse403 | disbandPartyResponse404 | disbandPartyResponse500) & {
  headers: Headers;
};

export type disbandPartyResponse = (disbandPartyResponseSuccess | disbandPartyResponseError)

export const getDisbandPartyUrl = (partyId: string,) => {


  

  return `/api/party/${partyId}/disband`
}

export const disbandParty = async (partyId: string, options?: RequestInit): Promise<disbandPartyResponse> => {
  
  const res = await fetch(getDisbandPartyUrl(partyId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: disbandPartyResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as disbandPartyResponse
}


/**
 * Removes a member from the party. Only the party leader can kick members.
The leader cannot kick themselves (use leave instead).

**Auth**: Only the party leader can kick members.
 * @summary Kick a member from the party
 */
export type kickMemberResponse200 = {
  data: void
  status: 200
}

export type kickMemberResponse400 = {
  data: ErrorResponse
  status: 400
}

export type kickMemberResponse401 = {
  data: ErrorResponse
  status: 401
}

export type kickMemberResponse403 = {
  data: ErrorResponse
  status: 403
}

export type kickMemberResponse404 = {
  data: ErrorResponse
  status: 404
}

export type kickMemberResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type kickMemberResponseSuccess = (kickMemberResponse200) & {
  headers: Headers;
};
export type kickMemberResponseError = (kickMemberResponse400 | kickMemberResponse401 | kickMemberResponse403 | kickMemberResponse404 | kickMemberResponse500) & {
  headers: Headers;
};

export type kickMemberResponse = (kickMemberResponseSuccess | kickMemberResponseError)

export const getKickMemberUrl = (partyId: string,) => {


  

  return `/api/party/${partyId}/kick`
}

export const kickMember = async (partyId: string,
    kickMemberRequest: KickMemberRequest, options?: RequestInit): Promise<kickMemberResponse> => {
  
  const res = await fetch(getKickMemberUrl(partyId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      kickMemberRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: kickMemberResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as kickMemberResponse
}


/**
 * Removes the requesting user from the party.
If the leader leaves, leadership is transferred to the oldest member.
If no members remain, the party is disbanded.

**Auth**: Requires authenticated user. Users can only leave for themselves.
 * @summary Leave a party
 */
export type leavePartyResponse200 = {
  data: void
  status: 200
}

export type leavePartyResponse400 = {
  data: ErrorResponse
  status: 400
}

export type leavePartyResponse401 = {
  data: ErrorResponse
  status: 401
}

export type leavePartyResponse404 = {
  data: ErrorResponse
  status: 404
}

export type leavePartyResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type leavePartyResponseSuccess = (leavePartyResponse200) & {
  headers: Headers;
};
export type leavePartyResponseError = (leavePartyResponse400 | leavePartyResponse401 | leavePartyResponse404 | leavePartyResponse500) & {
  headers: Headers;
};

export type leavePartyResponse = (leavePartyResponseSuccess | leavePartyResponseError)

export const getLeavePartyUrl = (partyId: string,) => {


  

  return `/api/party/${partyId}/leave`
}

export const leaveParty = async (partyId: string, options?: RequestInit): Promise<leavePartyResponse> => {
  
  const res = await fetch(getLeavePartyUrl(partyId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: leavePartyResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as leavePartyResponse
}


export type getPartyMembersResponse200 = {
  data: PartyMembersResponse
  status: 200
}

export type getPartyMembersResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getPartyMembersResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getPartyMembersResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getPartyMembersResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getPartyMembersResponseSuccess = (getPartyMembersResponse200) & {
  headers: Headers;
};
export type getPartyMembersResponseError = (getPartyMembersResponse401 | getPartyMembersResponse403 | getPartyMembersResponse404 | getPartyMembersResponse500) & {
  headers: Headers;
};

export type getPartyMembersResponse = (getPartyMembersResponseSuccess | getPartyMembersResponseError)

export const getGetPartyMembersUrl = (partyId: string,) => {


  

  return `/api/party/${partyId}/members`
}

export const getPartyMembers = async (partyId: string, options?: RequestInit): Promise<getPartyMembersResponse> => {
  
  const res = await fetch(getGetPartyMembersUrl(partyId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getPartyMembersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getPartyMembersResponse
}


/**
 * Starts a new movie round from the Review state.
Only the party leader can start a new round.
This resets the party to Created state and generates a new join code.
All members' ready states are reset to false.

**Auth**: Only the party leader can start a new round.
 * @summary Start a new movie round
 */
export type startNewRoundResponse200 = {
  data: NewRoundResponse
  status: 200
}

export type startNewRoundResponse400 = {
  data: ErrorResponse
  status: 400
}

export type startNewRoundResponse401 = {
  data: ErrorResponse
  status: 401
}

export type startNewRoundResponse403 = {
  data: ErrorResponse
  status: 403
}

export type startNewRoundResponse404 = {
  data: ErrorResponse
  status: 404
}

export type startNewRoundResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type startNewRoundResponseSuccess = (startNewRoundResponse200) & {
  headers: Headers;
};
export type startNewRoundResponseError = (startNewRoundResponse400 | startNewRoundResponse401 | startNewRoundResponse403 | startNewRoundResponse404 | startNewRoundResponse500) & {
  headers: Headers;
};

export type startNewRoundResponse = (startNewRoundResponseSuccess | startNewRoundResponseError)

export const getStartNewRoundUrl = (partyId: string,) => {


  

  return `/api/party/${partyId}/new-round`
}

export const startNewRound = async (partyId: string, options?: RequestInit): Promise<startNewRoundResponse> => {
  
  const res = await fetch(getStartNewRoundUrl(partyId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: startNewRoundResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as startNewRoundResponse
}


export type toggleReadyResponse200 = {
  data: void
  status: 200
}

export type toggleReadyResponse400 = {
  data: void
  status: 400
}

export type toggleReadyResponse401 = {
  data: ErrorResponse
  status: 401
}

export type toggleReadyResponse404 = {
  data: void
  status: 404
}

export type toggleReadyResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type toggleReadyResponseSuccess = (toggleReadyResponse200) & {
  headers: Headers;
};
export type toggleReadyResponseError = (toggleReadyResponse400 | toggleReadyResponse401 | toggleReadyResponse404 | toggleReadyResponse500) & {
  headers: Headers;
};

export type toggleReadyResponse = (toggleReadyResponseSuccess | toggleReadyResponseError)

export const getToggleReadyUrl = (partyId: string,) => {


  

  return `/api/party/${partyId}/ready`
}

export const toggleReady = async (partyId: string,
    setReadyRequest: SetReadyRequest, options?: RequestInit): Promise<toggleReadyResponse> => {
  
  const res = await fetch(getToggleReadyUrl(partyId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      setReadyRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: toggleReadyResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as toggleReadyResponse
}


/**
 * Transfers leadership to another party member.
Only the current leader can transfer leadership.

**Auth**: Only the party leader can transfer leadership.
 * @summary Transfer party leadership
 */
export type transferLeadershipResponse200 = {
  data: void
  status: 200
}

export type transferLeadershipResponse400 = {
  data: ErrorResponse
  status: 400
}

export type transferLeadershipResponse401 = {
  data: ErrorResponse
  status: 401
}

export type transferLeadershipResponse403 = {
  data: ErrorResponse
  status: 403
}

export type transferLeadershipResponse404 = {
  data: ErrorResponse
  status: 404
}

export type transferLeadershipResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type transferLeadershipResponseSuccess = (transferLeadershipResponse200) & {
  headers: Headers;
};
export type transferLeadershipResponseError = (transferLeadershipResponse400 | transferLeadershipResponse401 | transferLeadershipResponse403 | transferLeadershipResponse404 | transferLeadershipResponse500) & {
  headers: Headers;
};

export type transferLeadershipResponse = (transferLeadershipResponseSuccess | transferLeadershipResponseError)

export const getTransferLeadershipUrl = (partyId: string,) => {


  

  return `/api/party/${partyId}/transfer-leadership`
}

export const transferLeadership = async (partyId: string,
    transferLeadershipRequest: TransferLeadershipRequest, options?: RequestInit): Promise<transferLeadershipResponse> => {
  
  const res = await fetch(getTransferLeadershipUrl(partyId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      transferLeadershipRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: transferLeadershipResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as transferLeadershipResponse
}


