/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * cinematch-api
 * OpenAPI spec version: 0.1.0
 */
import type {
  ErrorResponse,
  GenreResponse,
  MovieResponse,
  RecommendedMoviesResponse,
  SearchMoviesParams,
  SearchResponse
} from '../../model';

import customInstance from '../../lib/orval-client';

export type getGenresResponse200 = {
  data: GenreResponse
  status: 200
}

export type getGenresResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getGenresResponse404 = {
  data: void
  status: 404
}

export type getGenresResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getGenresResponseSuccess = (getGenresResponse200) & {
  headers: Headers;
};
export type getGenresResponseError = (getGenresResponse401 | getGenresResponse404 | getGenresResponse500) & {
  headers: Headers;
};

export type getGenresResponse = (getGenresResponseSuccess | getGenresResponseError)

export const getGetGenresUrl = () => {


  

  return `/api/movie/genres`
}

export const getGenres = async ( options?: RequestInit): Promise<getGenresResponse> => {
  
  return customInstance<getGenresResponse>(getGetGenresUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type movieGetInfoResponse200 = {
  data: MovieResponse
  status: 200
}

export type movieGetInfoResponse401 = {
  data: ErrorResponse
  status: 401
}

export type movieGetInfoResponse404 = {
  data: ErrorResponse
  status: 404
}

export type movieGetInfoResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type movieGetInfoResponseSuccess = (movieGetInfoResponse200) & {
  headers: Headers;
};
export type movieGetInfoResponseError = (movieGetInfoResponse401 | movieGetInfoResponse404 | movieGetInfoResponse500) & {
  headers: Headers;
};

export type movieGetInfoResponse = (movieGetInfoResponseSuccess | movieGetInfoResponseError)

export const getMovieGetInfoUrl = (movieId: number,) => {


  

  return `/api/movie/info/${movieId}`
}

export const movieGetInfo = async (movieId: number, options?: RequestInit): Promise<movieGetInfoResponse> => {
  
  return customInstance<movieGetInfoResponse>(getMovieGetInfoUrl(movieId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getRecommendationsResponse200 = {
  data: RecommendedMoviesResponse
  status: 200
}

export type getRecommendationsResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getRecommendationsResponse404 = {
  data: void
  status: 404
}

export type getRecommendationsResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getRecommendationsResponseSuccess = (getRecommendationsResponse200) & {
  headers: Headers;
};
export type getRecommendationsResponseError = (getRecommendationsResponse401 | getRecommendationsResponse404 | getRecommendationsResponse500) & {
  headers: Headers;
};

export type getRecommendationsResponse = (getRecommendationsResponseSuccess | getRecommendationsResponseError)

export const getGetRecommendationsUrl = () => {


  

  return `/api/movie/recommend`
}

export const getRecommendations = async ( options?: RequestInit): Promise<getRecommendationsResponse> => {
  
  return customInstance<getRecommendationsResponse>(getGetRecommendationsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type searchMoviesResponse200 = {
  data: SearchResponse
  status: 200
}

export type searchMoviesResponse400 = {
  data: ErrorResponse
  status: 400
}

export type searchMoviesResponse401 = {
  data: ErrorResponse
  status: 401
}

export type searchMoviesResponse404 = {
  data: ErrorResponse
  status: 404
}

export type searchMoviesResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type searchMoviesResponseSuccess = (searchMoviesResponse200) & {
  headers: Headers;
};
export type searchMoviesResponseError = (searchMoviesResponse400 | searchMoviesResponse401 | searchMoviesResponse404 | searchMoviesResponse500) & {
  headers: Headers;
};

export type searchMoviesResponse = (searchMoviesResponseSuccess | searchMoviesResponseError)

export const getSearchMoviesUrl = (params: SearchMoviesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/movie/search?${stringifiedParams}` : `/api/movie/search`
}

export const searchMovies = async (params: SearchMoviesParams, options?: RequestInit): Promise<searchMoviesResponse> => {
  
  return customInstance<searchMoviesResponse>(getSearchMoviesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


